//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.SqlServer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATable
    {
        public double A { get; set; }
        public string B { get; set; }
        public int C { get; set; }
        public System.DateTime D { get; set; }
        public Nullable<bool> E { get; set; }
    }
}
