

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tracker.SqlServer.Entities
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TrackerEntities : DbContext
{
    public TrackerEntities()
        //: base("name=TrackerEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Audit> Audits { get; set; }

    public virtual DbSet<Priority> Priorities { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    public virtual DbSet<Task> Tasks { get; set; }

    public virtual DbSet<TaskExtended> TaskExtendeds { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductSummary> ProductSummaries { get; set; }

    public virtual DbSet<Item_2> Item_2 { get; set; }

}

}

