
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tracker.SqlServer.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Item_2
{

    public string ItemId { get; set; }

    public string ProductId { get; set; }

    public Nullable<decimal> ListPrice { get; set; }

    public Nullable<decimal> UnitCost { get; set; }

    public Nullable<int> Supplier { get; set; }

    public string Status { get; set; }

    public string Attr1 { get; set; }

    public string Attr2 { get; set; }

    public string Attr3 { get; set; }

    public string Attr4 { get; set; }

    public string Attr5 { get; set; }



    public virtual Product Product { get; set; }

}

}
