
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tracker.SqlServer.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public Product()
    {

        this.Items = new HashSet<Item>();

        this.Item_2 = new HashSet<Item_2>();

    }


    public string ProductId { get; set; }

    public string Category { get; set; }

    public string Name { get; set; }

    public string Descn { get; set; }



    public virtual ICollection<Item> Items { get; set; }

    public virtual ICollection<Item_2> Item_2 { get; set; }

}

}
