
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tracker.SqlServer.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Task
{

    public Task()
    {

        this.Audits = new HashSet<Audit>();

    }


    public int Id { get; set; }

    public int StatusId { get; set; }

    public Nullable<int> PriorityId { get; set; }

    public int CreatedId { get; set; }

    public string Summary { get; set; }

    public string Details { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> DueDate { get; set; }

    public Nullable<System.DateTime> CompleteDate { get; set; }

    public Nullable<int> AssignedId { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public System.DateTime ModifiedDate { get; set; }

    public byte[] RowVersion { get; set; }

    public string LastModifiedBy { get; set; }



    public virtual ICollection<Audit> Audits { get; set; }

    public virtual Priority Priority { get; set; }

    public virtual Status Status { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual TaskExtended TaskExtended { get; set; }

}

}
