//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Tracker.SqlServer.CodeFirst
{
    public partial class TrackerContext
        : System.Data.Entity.DbContext
    {
        static TrackerContext()
        {
            System.Data.Entity.Database.SetInitializer<TrackerContext>(null);
        }

        public System.Data.Entity.DbSet<Tracker.SqlServer.CodeFirst.Entities.Audit> Audits { get; set; }
        public System.Data.Entity.DbSet<Tracker.SqlServer.CodeFirst.Entities.Task> Tasks { get; set; }
        public System.Data.Entity.DbSet<Tracker.SqlServer.CodeFirst.Entities.User> Users { get; set; }
        public System.Data.Entity.DbSet<Tracker.SqlServer.CodeFirst.Entities.Priority> Priorities { get; set; }
        public System.Data.Entity.DbSet<Tracker.SqlServer.CodeFirst.Entities.Role> Roles { get; set; }
        public System.Data.Entity.DbSet<Tracker.SqlServer.CodeFirst.Entities.Status> Status { get; set; }
        public System.Data.Entity.DbSet<Tracker.SqlServer.CodeFirst.Entities.TaskExtended> TaskExtendeds { get; set; }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<System.Data.Entity.Infrastructure.IncludeMetadataConvention>();
            modelBuilder.Configurations.Add(new Tracker.SqlServer.CodeFirst.Mapping.AuditMap());
            modelBuilder.Configurations.Add(new Tracker.SqlServer.CodeFirst.Mapping.TaskMap());
            modelBuilder.Configurations.Add(new Tracker.SqlServer.CodeFirst.Mapping.UserMap());
            modelBuilder.Configurations.Add(new Tracker.SqlServer.CodeFirst.Mapping.PriorityMap());
            modelBuilder.Configurations.Add(new Tracker.SqlServer.CodeFirst.Mapping.RoleMap());
            modelBuilder.Configurations.Add(new Tracker.SqlServer.CodeFirst.Mapping.StatusMap());
            modelBuilder.Configurations.Add(new Tracker.SqlServer.CodeFirst.Mapping.TaskExtendedMap());

            InitializeMapping(modelBuilder);
        }
    }
}