//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.SqlCompact.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guid
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AlternateId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
