//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.SqlCompact.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskExtended
    {
        public int TaskId { get; set; }
        public string Browser { get; set; }
        public string OS { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
