//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.MySql.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public task()
        {
            this.audits = new HashSet<audit>();
        }
    
        public int Id { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public int CreatedId { get; set; }
        public string Summary { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<int> AssignedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public byte[] RowVersion { get; set; }
        public string LastModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<audit> audits { get; set; }
        public virtual priority priority { get; set; }
        public virtual status status { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual taskextended taskextended { get; set; }
    }
}
