//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tracker.SqlServer.CodeFirst.Mapping
{
    public partial class TaskExtendedMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Tracker.SqlServer.CodeFirst.Entities.TaskExtended>
    {
        public TaskExtendedMap()
        {
            // table
            ToTable("TaskExtended", "dbo");

            // keys
            HasKey(t => t.TaskId);

            // Properties
            Property(t => t.TaskId)
                .HasColumnName("TaskId")
                .IsRequired();
            Property(t => t.Browser)
                .HasColumnName("Browser")
                .HasMaxLength(200)
                .IsOptional();
            Property(t => t.Os)
                .HasColumnName("OS")
                .HasMaxLength(150)
                .IsOptional();
            Property(t => t.CreatedDate)
                .HasColumnName("CreatedDate")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();
            Property(t => t.RowVersion)
                .HasColumnName("RowVersion")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed)
                .HasMaxLength(8)
                .IsRowVersion()
                .IsRequired();

            // Relationships
            HasRequired(t => t.Task)
                .WithOptional(t => t.TaskExtended)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}

