//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tracker.SqlServer.CodeFirst.Mapping
{
    public partial class TaskMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Tracker.SqlServer.CodeFirst.Entities.Task>
    {
        public TaskMap()
        {
            // table
            ToTable("Task", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.StatusId)
                .HasColumnName("StatusId")
                .IsRequired();
            Property(t => t.PriorityId)
                .HasColumnName("PriorityId")
                .IsOptional();
            Property(t => t.CreatedId)
                .HasColumnName("CreatedId")
                .IsRequired();
            Property(t => t.Summary)
                .HasColumnName("Summary")
                .IsRequired();
            Property(t => t.Details)
                .HasColumnName("Details")
                .IsOptional();
            Property(t => t.StartDate)
                .HasColumnName("StartDate")
                .IsOptional();
            Property(t => t.DueDate)
                .HasColumnName("DueDate")
                .IsOptional();
            Property(t => t.CompleteDate)
                .HasColumnName("CompleteDate")
                .IsOptional();
            Property(t => t.AssignedId)
                .HasColumnName("AssignedId")
                .IsOptional();
            Property(t => t.CreatedDate)
                .HasColumnName("CreatedDate")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();
            Property(t => t.RowVersion)
                .HasColumnName("RowVersion")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed)
                .IsRowVersion()
                .IsRequired();
            Property(t => t.LastModifiedBy)
                .HasColumnName("LastModifiedBy")
                .IsOptional();

            // Relationships
            HasOptional(t => t.Priority)
                .WithMany(t => t.Tasks)
                .HasForeignKey(d => d.PriorityId);
            HasRequired(t => t.Status)
                .WithMany(t => t.Tasks)
                .HasForeignKey(d => d.StatusId);
            HasOptional(t => t.AssignedUser)
                .WithMany(t => t.AssignedTasks)
                .HasForeignKey(d => d.AssignedId);
            HasRequired(t => t.CreatedUser)
                .WithMany(t => t.CreatedTasks)
                .HasForeignKey(d => d.CreatedId);

            InitializeMapping();
        }
    }
}

