//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tracker.SqlServer.CodeFirst.Mapping
{
    public partial class UserMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Tracker.SqlServer.CodeFirst.Entities.User>
    {
        public UserMap()
        {
            // table
            ToTable("User", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.EmailAddress)
                .HasColumnName("EmailAddress")
                .IsRequired();
            Property(t => t.FirstName)
                .HasColumnName("FirstName")
                .IsOptional();
            Property(t => t.LastName)
                .HasColumnName("LastName")
                .IsOptional();
            Property(t => t.Avatar)
                .HasColumnName("Avatar")
                .IsOptional();
            Property(t => t.CreatedDate)
                .HasColumnName("CreatedDate")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();
            Property(t => t.RowVersion)
                .HasColumnName("RowVersion")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed)
                .IsRowVersion()
                .IsRequired();
            Property(t => t.PasswordHash)
                .HasColumnName("PasswordHash")
                .IsRequired();
            Property(t => t.PasswordSalt)
                .HasColumnName("PasswordSalt")
                .IsRequired();
            Property(t => t.Comment)
                .HasColumnName("Comment")
                .IsOptional();
            Property(t => t.IsApproved)
                .HasColumnName("IsApproved")
                .IsRequired();
            Property(t => t.LastLoginDate)
                .HasColumnName("LastLoginDate")
                .IsOptional();
            Property(t => t.LastActivityDate)
                .HasColumnName("LastActivityDate")
                .IsRequired();
            Property(t => t.LastPasswordChangeDate)
                .HasColumnName("LastPasswordChangeDate")
                .IsOptional();
            Property(t => t.AvatarType)
                .HasColumnName("AvatarType")
                .IsOptional();

            // Relationships

            InitializeMapping();
        }
    }
}

