//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("EntityFramework.Extended (.NET 4.5)")]
[assembly: System.Reflection.AssemblyDescription("Entity Framework extensions library. Built for .NET 4.5")]
[assembly: System.Reflection.AssemblyCompany("LoreSoft")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2015 LoreSoft")]
[assembly: System.Reflection.AssemblyVersion("6.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("6.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("6.1.0.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyProduct = "EntityFramework.Extended (.NET 4.5)";
    
    internal const string AssemblyDescription = "Entity Framework extensions library. Built for .NET 4.5";
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyCopyright = "Copyright © 2015 LoreSoft";
    
    internal const string AssemblyVersion = "6.0.0.0";
    
    internal const string AssemblyFileVersion = "6.1.0.0";
    
    internal const string AssemblyInformationalVersion = "6.1.0.0";
    
    private ThisAssembly() {
    }
}
