//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("EntityFramework.Extended")]
[assembly: AssemblyCompany("LoreSoft")]
[assembly: AssemblyCopyright("Copyright © 2011 LoreSoft")]
[assembly: AssemblyVersion("1.0.0.5")]
[assembly: AssemblyFileVersion("1.0.0.5")]
[assembly: AssemblyInformationalVersion("1.0.0.5")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyProduct = "EntityFramework.Extended";
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyCopyright = "Copyright © 2011 LoreSoft";
    
    internal const string AssemblyVersion = "1.0.0.5";
    
    internal const string AssemblyFileVersion = "1.0.0.5";
    
    internal const string AssemblyInformationalVersion = "1.0.0.5";
    
    private ThisAssembly() {
    }
}
