//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("EntityFramework.Extended (.NET 4.5)")]
[assembly: AssemblyDescription("Entity Framework extensions library. Built for .NET 4.5")]
[assembly: AssemblyCompany("LoreSoft")]
[assembly: AssemblyCopyright("Copyright © 2014 LoreSoft")]
[assembly: AssemblyVersion("6.0.0.0")]
[assembly: AssemblyFileVersion("6.1.0.0")]
[assembly: AssemblyInformationalVersion("6.1.0.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyProduct = "EntityFramework.Extended (.NET 4.5)";
    
    internal const string AssemblyDescription = "Entity Framework extensions library. Built for .NET 4.5";
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyCopyright = "Copyright © 2014 LoreSoft";
    
    internal const string AssemblyVersion = "6.0.0.0";
    
    internal const string AssemblyFileVersion = "6.1.0.0";
    
    internal const string AssemblyInformationalVersion = "6.1.0.0";
    
    private ThisAssembly() {
    }
}
